@hostname = localhost
@port = 1234
@baseUrl = http://{{hostname}}:{{port}}/api
@baseUrlNoApi = http://{{hostname}}:{{port}}
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc3MTc5OTkwOCwiZXhwIjoxNzcxODAzNTA4fQ.ygsZ4szWRvMsXIPdSrtqa_rYttVUDDJUfU9pHrvqvJQ

### Obtener token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "xxxxx"
}

### Ingresar a dashboard
GET {{baseUrlNoApi}}/dashboard
Authorization: Bearer {{adminToken}}

### Ingresar a dashboard sin token
GET {{baseUrlNoApi}}/dashboard
