@hostname = localhost
@port = 1234
@baseUrl = http://{{hostname}}:{{port}}/api

### Obtener todos los proyectos
GET {{baseUrl}}/projects

###

### Crear un nuevo proyecto
POST {{baseUrl}}/projects
Content-Type: application/json

{
    "title": "PortFolio-Node",
    "description": "Portfolio de ejemplo de estructuracion de proyecto con MVC",
    "technologies": "Node,JavaScript,CSS,HTML,Express",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzsM6zsSVj3LttmwxNWDO-TC7EpxXKvABpog&s",
    "repo_url": "https://github.com/Stresadiz/Portfolio-Node",
    "live_url": "https://github.com/Stresadiz/Portfolio-Node"
}

### Crear proyecto vacio
POST {{baseUrl}}/projects
Content-Type: application/json

{
    "description": "Este no tiene título, debería fallar"
}

### Borrar proyecto
DELETE {{baseUrl}}/projects/8